name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    # Add NVM and PM2 Path
    - name: Load NVM and Add PM2 to Path
      run: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
        export PATH="$HOME/.nvm/versions/node/v22.14.0/bin:$PATH"
        echo "NVM and PM2 path loaded."

    # Restart PM2
    - name: Restart PM2 Process
      run: pm2 restart index.js
